### ISSUE TITLE
template="table" gives blank result

### ISSUE THREAD

**Issue by adelenelai** [cbouy/mols2grid#27]
Hi, I love mols2grid! Thanks for the hard work.

I'm having the inverse problem of what is described here: https://github.com/cbouy/mols2grid/issues/8

template="table" gives blank output, but template="pages" works fine. 

There are no NaNs in my pandas dataframe.

Using mols2grid 0.2.1 with rdkit 2021.09.4 in a conda environment, Jinja2 3.0.2, pandas 1.4.0 on macOS, browser is Brave Version 1.35.104.

Thanks!

**Comment by cbouy** [comment]
Hi @adelenelai,

When you say "blank output", you mean there's really nothing at all, or it's a grid with "None" instead of images like here:
![image](https://user-images.githubusercontent.com/27850535/160923671-7754a770-49f7-42c3-b607-c2fa62799988.png)

If it's as in the image, I'm currently working on a fix. I haven't given much love to the "table" template so sorry for the inconvenience!

If it's not, then we might have another problem! Could you share the code that produces the issue?

Best,
Cedric

**Comment by cbouy** [comment]
@adelenelai you can try the latest update (0.2.2, only available from pip for now) and see if it solves your issue

**Comment by adelenelai** [comment]
@cbouy thanks! works now with 0.2.2. Closing.
